version: '3.1'

services:


  frontend:
    build: ./frontend  # Build context is the current directory (./) relative to the Dockerfile
    image: frontend-image
    ports:
      - "3000:3000"  # Map container port 3000 to host port 3000
    networks:
      - bazar-network
    volumes:
      - ./frontend:/app:ro

  catalog-server:
    build: ./catalog_server  # Build context is ./catalog_server relative to the Dockerfile
    image: catalog-server-image
    ports:
      - "4000:4000" 
    networks:
      - bazar-network  

  order-server:
    build: ./order_server  # Build context is ./order_server relative to the Dockerfile
    image: order-server-image  
    ports:
      - "5000:5000"  
    networks:
      - bazar-network

networks:
  bazar-network:  
    external: false  # Optional: Set to true if you want to expose the network to external containers
