version: '3.1'

services:


  frontend:
    build: ./frontend  
    image: frontend-image
    ports:
      - "3000:3000"  
    networks:
      - bazar-network
    volumes:
      - ./frontend:/app:ro

  catalog-server:
    build: ./catalog_server 
    image: catalog-server-image
    ports:
      - "4000:4000" 
    networks:
      - bazar-network  

  order-server:
    build: ./order_server  
    image: order-server-image  
    ports:
      - "5000:5000"  
    networks:
      - bazar-network

networks:
  bazar-network:  
    external: false  # Optional flag to indicate that the network is external
